Improvements for CI workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,17 +20,20 @@ on:
 env:
   pkgname: QBrainwaveOSC
   IDENTITY_NAME: ${{ secrets.IDENTITY_NAME }}
-# note: build and publish builds with msvc is disabled until fix problem with KISSRingBuffer
+
 jobs:
   build:
     strategy:
       matrix:
        include:
-        - { name: "windows", os: windows-latest, flags: '-G"Visual Studio 17 2022"', shell: 'msys2 {0}', deps-prefix: "D:/deps", aqt-os: "windows", aqt-arch: "win64_msvc2019_64", aqt-prefix: "/opt/Qt", aqt-subdir: "msvc2019_64", qt-version: '6.5.1', msystem: 'UCRT64' }
-        - { name: "windows-legacy", os: windows-latest, flags: "", shell: 'msys2 {0}', deps-prefix: "/opt/deps", aqt-os: "windows", aqt-arch: "win64_mingw81", aqt-prefix: "/opt/Qt", aqt-subdir: "mingw81_64", qt-version: '5.15.2', msystem: 'MINGW64' }
-        - { name: "linux", os: ubuntu-latest, flags: "", shell: 'bash', deps-prefix: "/home/runner/deps", aqt-os: "linux", aqt-arch: "gcc_64", aqt-prefix: "/home/runner/Qt", aqt-subdir: "gcc_64", qt-version: '6.5.1'}
-        - { name: "macos-universal", os: macos-latest, flags: "-DCMAKE_OSX_ARCHITECTURES=\"x86_64;arm64\"", shell: 'bash', deps-prefix: "/Users/runner/deps", aqt-os: "mac", aqt-arch: "", aqt-prefix: "/Users/runner/Qt", aqt-subdir: "macos", qt-version: '6.5.1'}
-        - { name: "macos-legacy", os: macos-latest, flags: "-DCMAKE_OSX_DEPLOYMENT_TARGET=\"10.13\" -DCMAKE_OSX_ARCHITECTURES=\"x86_64\"", shell: 'bash', deps-prefix: "/Users/runner/deps", aqt-os: "mac", aqt-arch: "", aqt-prefix: "/Users/runner/Qt", aqt-subdir: "clang_64", qt-version: '5.15.2' }
+        - { name: "windows-qt6-msvc", os: windows-latest, flags: '-G"Visual Studio 17 2022"', shell: 'msys2 {0}', deps-prefix: "D:/deps", aqt-os: "windows", aqt-arch: "win64_msvc2019_64", aqt-prefix: "D:/Qt", aqt-subdir: "msvc2019_64", qt-version: '6.5.1', msystem: 'UCRT64', build-fftw: true }
+        - { name: "windows-qt5-msvc", os: windows-latest, flags: '-G"Visual Studio 17 2022"', shell: 'msys2 {0}', deps-prefix: "D:/deps", aqt-os: "windows", aqt-arch: "win64_msvc2019_64", aqt-prefix: "D:/Qt", aqt-subdir: "msvc2019_64", qt-version: '5.15.2', msystem: 'UCRT64', build-fftw: true }
+        - { name: "windows-qt6-mingw", os: windows-latest, flags: "", shell: 'msys2 {0}', deps-prefix: "D:/deps", aqt-os: "none", aqt-arch: "win64_msvc2019_64", aqt-prefix: "D:/Qt", aqt-subdir: "msvc2019_64", qt-version: '6.5.1', msystem: 'UCRT64', build-fftw: false }
+        - { name: "windows-qt5-mingw", os: windows-latest, flags: "", shell: 'msys2 {0}', deps-prefix: "D:/deps", aqt-os: "none", aqt-arch: "win64_mingw73", aqt-prefix: "D:/Qt", aqt-subdir: "mingw73_64", qt-version: '5.12.12', msystem: 'MINGW64', build-fftw: false }
+        - { name: "linux-qt6", os: ubuntu-latest, flags: "", shell: 'bash', deps-prefix: "/home/runner/deps", aqt-os: "none", aqt-arch: "gcc_64", aqt-prefix: "/home/runner/Qt", aqt-subdir: "gcc_64", qt-version: '6.5.1', build-fftw: false }
+        - { name: "linux-qt5", os: ubuntu-22.04, flags: "", shell: 'bash', deps-prefix: "/home/runner/deps", aqt-os: "none", aqt-arch: "gcc_64", aqt-prefix: "/home/runner/Qt", aqt-subdir: "gcc_64", qt-version: '5.15.2', build-fftw: false }
+        - { name: "macos-qt6-universal", os: macos-latest, flags: "-DCMAKE_OSX_ARCHITECTURES=\"x86_64;arm64\"", shell: 'bash', deps-prefix: "/Users/runner/deps", aqt-os: "mac", aqt-arch: "", aqt-prefix: "/Users/runner/Qt", aqt-subdir: "macos", qt-version: '6.5.1', build-fftw: true }
+        - { name: "macos-qt5-legacy", os: macos-latest, flags: "-DCMAKE_OSX_DEPLOYMENT_TARGET=\"10.13\" -DCMAKE_OSX_ARCHITECTURES=\"x86_64\"", shell: 'bash', deps-prefix: "/Users/runner/deps", aqt-os: "mac", aqt-arch: "", aqt-prefix: "/Users/runner/Qt", aqt-subdir: "clang_64", qt-version: '5.15.2', build-fftw: true }
     runs-on: ${{matrix.os}}
     defaults:
       run:
@@ -77,6 +80,10 @@ jobs:
                 ${MINGW_PACKAGE_PREFIX}-python-wheel \
                 ${MINGW_PACKAGE_PREFIX}-python-patch-ng \
                 ${MINGW_PACKAGE_PREFIX}-cmake \
+                ${MINGW_PACKAGE_PREFIX}-gles-headers \
+                ${MINGW_PACKAGE_PREFIX}-glew \
+                ${MINGW_PACKAGE_PREFIX}-glfw \
+                ${MINGW_PACKAGE_PREFIX}-angleproject \
                 ${MINGW_PACKAGE_PREFIX}-nsis
 
     - name: Setup windows env
@@ -156,10 +163,14 @@ jobs:
            echo "INSTALL_PREFIX=$INSTALL_PREFIX" >> $GITHUB_ENV
 
     - name: Install AQT
+      shell: 'bash'
+      if: ${{matrix.aqt-os != 'none'}}
       run: |    
            python3 -m pip install --break-system-packages --user aqtinstall
 
-    - name: Install Qt
+    - name: Install Qt (with AQT)
+      shell: 'bash'
+      if: ${{matrix.aqt-os != 'none'}}
       run: |
            AQT_INSTALL="python3 -m aqt install-qt -O ${{matrix.aqt-prefix}} ${{matrix.aqt-os}} desktop ${{matrix.qt-version}} ${{matrix.aqt-arch}}"
            QT6_MODULES=(qtconnectivity qtserialport qtcharts)
@@ -174,8 +185,41 @@ jobs:
                    ${AQT_INSTALL} -m $i
                done
            fi
+    
+    - name: Install QT (mingw)
+      if: ${{matrix.aqt-os == 'none' && runner.os == 'Windows'}}
+      run: |
+          QTVER=${{matrix.qt-version}}
+          QTVER=${QTVER:0:1}
+          pacman -S --noconfirm \
+                ${MINGW_PACKAGE_PREFIX}-qt${QTVER}-connectivity \
+                ${MINGW_PACKAGE_PREFIX}-qt${QTVER}-serialport \
+                ${MINGW_PACKAGE_PREFIX}-qt${QTVER}-charts
 
+    - name: Install QT (linux)
+      if: ${{matrix.aqt-os == 'none' && runner.os == 'Linux'}}
+      run: |
+          QTVER=${{matrix.qt-version}}
+          QTVER=${QTVER:0:1}
+          if [[ ${{matrix.qt-version}} == 6.* ]]; then
+              sudo apt-get install -y qt6-base-dev \
+                                      qt6-base-dev-tools \
+                                      qt6-serialport-dev \
+                                      qt6-charts-dev \
+                                      qt6-connectivity-dev \
+                                      qt6-tools-dev \
+                                      qt6-tools-dev-tools \
+                                      qmake6
+          else
+              sudo apt-get install -y qtbase5-dev \
+                                      libqt5charts5-dev \
+                                      libqt5serialport5-dev \
+                                      qtconnectivity5-dev \
+                                      qt5-qmake
+          fi
+      
     - name: FETCH FFTW3
+      if: ${{matrix.build-fftw}}
       run: |
           wget https://www.fftw.org/fftw-3.3.10.tar.gz
           tar -vxzf fftw-3.3.10.tar.gz
@@ -185,22 +229,35 @@ jobs:
           else
               echo "FFTW_BUILD_DIR="${FFTW_BUILD_DIR}"" >> $GITHUB_ENV
           fi
-    
+
     - name: Compile FFTW3 (WINDOWS)
-      if: ${{matrix.name == 'windows'}}
+      if: ${{( (matrix.name == 'windows-qt6-msvc') || (matrix.name == 'windows-qt5-msvc') ) && matrix.build-fftw}}
       shell: pwsh
       run: |
           cmake -S fftw-3.3.10 -B ${{env.WORKDIR}}/fftw-build ${{matrix.flags}} -DCMAKE_INSTALL_PREFIX=${{env.DEPSPATH}}
           cmake --build ${{env.FFTW_BUILD_DIR}} --config Release
-    
+
     - name: Compile FFTW3 (POSIX)
-      if: ${{matrix.name != 'windows'}}
+      if: ${{( (matrix.name != 'windows-qt6-msvc') && (matrix.name != 'windows-qt5-msvc') ) && matrix.build-fftw}}
       run: |
           cmake -S fftw-3.3.10 -B ${{env.WORKDIR}}/fftw-build ${{matrix.flags}} -DCMAKE_INSTALL_PREFIX=${{env.DEPSPATH}}
           cmake --build ${{env.FFTW_BUILD_DIR}}
-    
+
     - name: Install FFTW3
+      if: ${{matrix.build-fftw}}
       run: cmake --install ${{env.FFTW_BUILD_DIR}}
+
+    - name: Install FFTW3 (MinGW)
+      if: ${{!(matrix.build-fftw) && (runner.os == 'Windows')}}
+      shell: 'msys2 {0}'
+      run: |
+          pacman -S --noconfirm \
+                ${MINGW_PACKAGE_PREFIX}-fftw
+
+    - name: Install FFTW3 (Linux)
+      if: ${{!(matrix.build-fftw) && (runner.os == 'Linux')}}
+      run: |
+          sudo apt-get install -y libfftw3-dev
 
     - name: Checkout Repo
       uses: actions/checkout@v3
@@ -216,11 +273,11 @@ jobs:
                  -DCMAKE_PREFIX_PATH="${{env.AQTPATH}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}};${{env.DEPSPATH}}"
 
     - name: Compile Code (POSIX)
-      if: ${{matrix.name != 'windows'}}
+      if: ${{(matrix.name != 'windows-qt6-msvc') && (matrix.name != 'windows-qt5-msvc')}}
       run: cmake --build ${{env.WORKDIR}}/build
 
     - name: Compile Code (WINDOWS)
-      if: ${{matrix.name == 'windows'}}
+      if: ${{(matrix.name == 'windows-qt6-msvc') || (matrix.name == 'windows-qt5-msvc')}}
       shell: pwsh
       run: cmake --build ${{github.workspace}}/build --config Release  
 
@@ -258,7 +315,17 @@ jobs:
       run: |
            export ARTIFACT_DIR=${{env.WORKDIR}}/${PACKAGE_NAME}
            find "${{env.DEPSPATH}}" -name "*.dll"  -exec cp {} ${{env.APPDIR}}/ \;
-           ${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}/bin/windeployqt.exe ${{env.APPDIR}}/
+           if [[ ${{matrix.aqt-os }} == 'none' ]]; then
+               windeployqt --release ${{env.APPDIR}}/ || echo "::warning::Unknown error"
+           else
+               ${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}/bin/windeployqt.exe --release ${{env.APPDIR}}/
+           fi
+           if [[ ${{matrix.aqt-os }} == 'none' ]]; then
+            echo "::notice:: Deploying additional libs"
+            for i in $(ldd ${{env.APPDIR}}/${{env.pkgname}} | cut -f 3 -d " " | grep "/bin/")
+             do cp -v $i ${{env.APPDIR}}/
+            done
+           fi
            mkdir $ARTIFACT_DIR || echo "::warning::${ARTIFACT_DIR} already exists"
            cd $ARTIFACT_DIR
            cpack --config ${{env.WORKDIR}}/build/CPackConfig.cmake -G NSIS -V
@@ -269,15 +336,13 @@ jobs:
     
     - name: Create AppImage
       if: ${{runner.os == 'Linux'}}
-      env:
-          QTDIR: ${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}
-          QMAKE: ${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}/bin/qmake
       run: | 
-           echo "::notice:: QMAKE=${QMAKE}"
-           sudo bash -c "echo ${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}/lib > /etc/ld.so.conf.d/aqt.conf"
-           sudo bash -c "echo ${{matrix.deps-prefix}}/lib > /etc/ld.so.conf.d/deps.conf"
-           sudo rm /etc/ld.so.cache
-           sudo ldconfig
+           if [[ ${{matrix.aqt-os}} == "linux" ]]; then
+               sudo bash -c "echo ${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}/lib > /etc/ld.so.conf.d/aqt.conf"
+               sudo bash -c "echo ${{matrix.deps-prefix}}/lib > /etc/ld.so.conf.d/deps.conf"
+               sudo rm /etc/ld.so.cache
+               sudo ldconfig
+           fi
            echo "::group:: Downloading linux deploy"
                wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
                wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
@@ -289,8 +354,11 @@ jobs:
            ICONFILE=$(find ${{ env.APPDIR }} -name *.png)
            DESKTOPFILE=$(find ${{env.APPDIR}} -name *.desktop)
            EXECFILE=$(find ${{env.APPDIR}} -name ${{env.pkgname}} -type f -executable)
-           export PATH=${QTDIR}/bin:${PATH}
-           export QT_INSTALL_PLUGINS=${QTDIR}/plugins/
+           if [[ ${{matrix.aqt-os}} == "linux" ]]; then
+               export QTDIR=${{matrix.aqt-prefix}}/${{matrix.qt-version}}/${{matrix.aqt-subdir}}
+               export QMAKE=${QTDIR}/bin/qmake
+               export QT_INSTALL_PLUGINS=${QTDIR}/plugins/
+           fi
            echo "::group:: Linux deploy QT"
                ./${LINUXDEPLOY} \
                    --appdir=${APPDIR} \
@@ -298,14 +366,13 @@ jobs:
                    --icon-file=${ICONFILE} \
                    --desktop-file=${DESKTOPFILE} \
                    --plugin qt
-                cp -Rv $QT_INSTALL_PLUGINS/generic ${APPDIR}/usr/plugins/ || echo "::warning:: generic plugin not found"
            echo "::endgroup::"
            echo "::group:: Creating AppImage"
                ./${LINUXDEPLOY} --appdir=${APPDIR} --output=appimage
-               mv ${{env.pkgname}}*.AppImage ${PACKAGE_NAME}.AppImage
-               export APPIMAGEDIR=${{github.workspace}}/${PACKAGE_NAME}
+               mv ${{env.pkgname}}*.AppImage ${{env.pkgname}}-${{matrix.name}}.AppImage
+               export APPIMAGEDIR=${{github.workspace}}/${{env.pkgname}}-${{matrix.name}}
                mkdir $APPIMAGEDIR || echo "::warning::${APPIMAGEDIR} already exists"
-               cp ${PACKAGE_NAME}.AppImage ${PACKAGE_NAME}
+               cp ${{env.pkgname}}-${{matrix.name}}.AppImage ${{env.pkgname}}-${{matrix.name}}
            echo "::endgroup::"
     
 #    - name: Setup tmate session
@@ -341,32 +408,50 @@ jobs:
       - name: Get macOS universal binary
         uses: actions/download-artifact@v3
         with:
-          name: ${{env.pkgname}}-macos-universal
-          path: ${{github.workspace}}/${{env.pkgname}}-macos-universal
+          name: ${{env.pkgname}}-macos-qt6-universal
+          path: ${{github.workspace}}/${{env.pkgname}}-macos-qt6-universal
 
       - name: Get macOS legacy binary
         uses: actions/download-artifact@v3
         with:
-          name: ${{env.pkgname}}-macos-legacy
-          path: ${{github.workspace}}/${{env.pkgname}}-macos-legacy
+          name: ${{env.pkgname}}-macos-qt5-legacy
+          path: ${{github.workspace}}/${{env.pkgname}}-macos-qt5-legacy
 
-      - name: Get Linux binary
+      - name: Get Linux binary (QT6)
         uses: actions/download-artifact@v3
         with:
-          name: ${{env.pkgname}}-linux
-          path: ${{github.workspace}}/${{env.pkgname}}-linux
+          name: ${{env.pkgname}}-linux-qt6
+          path: ${{github.workspace}}/${{env.pkgname}}-linux-qt6
 
-      - name: Get Windows binary
+      - name: Get Linux binary (QT5)
         uses: actions/download-artifact@v3
         with:
-          name: ${{env.pkgname}}-windows
-          path: ${{github.workspace}}/${{env.pkgname}}-windows
+          name: ${{env.pkgname}}-linux-qt5
+          path: ${{github.workspace}}/${{env.pkgname}}-linux-qt5
 
-      - name: Get Windows legacy binary
+      - name: Get Windows binary (Qt6 MSVC)
         uses: actions/download-artifact@v3
         with:
-          name: ${{env.pkgname}}-windows-legacy
-          path: ${{github.workspace}}/${{env.pkgname}}-windows-legacy
+          name: ${{env.pkgname}}-windows-qt6-msvc
+          path: ${{github.workspace}}/${{env.pkgname}}-windows-qt6-msvc
+
+      - name: Get Windows binary (Qt5 MSVC)
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{env.pkgname}}-windows-qt5-msvc
+          path: ${{github.workspace}}/${{env.pkgname}}-windows-qt5-msvc
+
+      - name: Get Windows binary (Qt6 MINGW)
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{env.pkgname}}-windows-qt6-mingw
+          path: ${{github.workspace}}/${{env.pkgname}}-windows-qt6-mingw
+
+      - name: Get Windows (Qt5 MinGW)
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{env.pkgname}}-windows-qt5-mingw
+          path: ${{github.workspace}}/${{env.pkgname}}-windows-qt5-mingw
 
       - if: github.event_name == 'push' # this is a snapshot build. create a release and upload binaries
         name: Create Snapshot Release
@@ -377,11 +462,14 @@ jobs:
           generate_release_notes: true
           prerelease: true
           files: |
-            ${{github.workspace}}/${{env.pkgname}}-macos-universal/*
-            ${{github.workspace}}/${{env.pkgname}}-macos-legacy/*
-            ${{github.workspace}}/${{env.pkgname}}-linux/*
-            ${{github.workspace}}/${{env.pkgname}}-windows-legacy/*
-            ${{github.workspace}}/${{env.pkgname}}-windows/*
+            ${{github.workspace}}/${{env.pkgname}}-macos-qt6-universal/*
+            ${{github.workspace}}/${{env.pkgname}}-macos-qt5-legacy/*
+            ${{github.workspace}}/${{env.pkgname}}-linux-qt6/*
+            ${{github.workspace}}/${{env.pkgname}}-linux-qt5/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt6-mingw/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt5-mingw/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt6-msvc/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt5-msvc/*
 
       - if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v') # this is a versioned build. check if release already exists
         name: Find Existing Release
@@ -402,8 +490,11 @@ jobs:
           generate_release_notes: true
           prerelease: false
           files: |
-            ${{github.workspace}}/${{env.pkgname}}-macos-universal/*
-            ${{github.workspace}}/${{env.pkgname}}-macos-legacy/*
-            ${{github.workspace}}/${{env.pkgname}}-windows/*
-            ${{github.workspace}}/${{env.pkgname}}-linux/*
-            ${{github.workspace}}/${{env.pkgname}}-windows-legacy/*
+            ${{github.workspace}}/${{env.pkgname}}-macos-qt6-universal/*
+            ${{github.workspace}}/${{env.pkgname}}-macos-qt5-legacy/*
+            ${{github.workspace}}/${{env.pkgname}}-linux-qt6/*
+            ${{github.workspace}}/${{env.pkgname}}-linux-qt5/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt6-mingw/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt5-mingw/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt6-msvc/*
+            ${{github.workspace}}/${{env.pkgname}}-windows-qt5-msvc/*
